### ISSUE TITLE
Image Recognition

### ISSUE THREAD

**Issue by karinadwi** [alankrantas/TeachableMachine-p5js-serialport#2]
thank you for making the image recognition program, on p5.js it works fine, but the output on Arduino does not turn on, only in programs outside serial.available it is on. thankyou
![Screenshot (380)](https://user-images.githubusercontent.com/80663984/111105628-ff948480-8585-11eb-80c1-83e032bfb77f.png)
![WhatsApp Image 2021-03-15 at 12 07 45 PM](https://user-images.githubusercontent.com/80663984/111106177-243d2c00-8587-11eb-8140-a5a2f33e0230.jpeg)

this is the arduino program

**Comment by alankrantas** [comment]
I think the issue is: your code turns on LED at pin 7 when it receive "2" via the serial port, but nothing else. So the LED 7 remains on no matter what you do afterwards.

I assume you're making a mask detector. So I would train the teachable machine like this:

* Label "0" = no people
* Label "1" = people (or you) with no mask
* Label "2" = people (or you) with mask

So you have to do things according to these conditions. For example, I would use two LEDs as warning/OK lights. When the Arduino receive "0", clear all LEDs since there's no one present. If it's "1", turn on the warning LED and turn off the OK LED, and do the opposite when it's "2". LEDs wouldn't change status unless you explicitly tell them to do so.

You might need to learn more about how C++'s ```switch``` and Arduino's ```digitalWrite()``` works, if you are not yet familiar with them.

**Comment by karinadwi** [comment]
So what do you think is wrong with this project? why my led on port 7 does not turn on, while on p5.js it is clear that the condition "2" has been detected🥺 and I think the program on My Arduino when condition "2" then led 7 will light up. Thankyou, I hope you answer 🥺

**Comment by alankrantas** [comment]
Does your LED 7 only turn on once after uploading, or it never turn on even after you reset the Arduino?

Also, how do you connect your LEDs?

pin -> resistor -> LED -> GND

or

5V -> resistor -> LED -> pin?

I'm in office right now; later I'll write a code which can monitor/simulate data from the teachable machine. If this code works, then something is wrong with the serial port communication.

**Comment by karinadwi** [comment]
I have tried led 7 with arduino program without connecting to serial, and it works. I connected the pin -> resistor -> LED -> GND.

Ok, Sorry. I'll be waiting 🙂

**Comment by alankrantas** [comment]
![1](https://user-images.githubusercontent.com/44191076/111160495-1c0bdd80-85d5-11eb-9b49-f9ad97cdba09.jpg)

Did you set the COM port in the sketch.js file? (This file would also print out the COM port list found on your computer.) And did you open the correct port in p5.serialcontrol after flashing code onto the Arduino?

I just remembered that I can't monitor the serial port from outside while p5.serialcontrol opens the channel. But you can still test it in some way.

I changed the Arduino code a bit:

```c++
char result = '0';

void setup() {
  Serial.begin(9600);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
}

void loop() {
  if (Serial.available() > 0) {
    result = Serial.read();
  }
  switch (result) {
    case '1':
      digitalWrite(7, HIGH);
      digitalWrite(8, LOW);
      break;
    case '2':
      digitalWrite(7, LOW);
      digitalWrite(8, HIGH);
      break;
    default:
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
  }
}
```

You can also open the Arduino serial monitor (close the COM port in p5.serialcontrol first), make sure the baud rate is 9600 and select "no line ending". Type 0, 1 or 2 into the window, and you can thus simulate the input from p5.js.

**Comment by karinadwi** [comment]
Oooo I see.. So for example, if I want to make a program using serial software in this case, is it not possible? as an example using the mini dfplayer

**Comment by alankrantas** [comment]
Well, it's possible to read software serial port from the computer, but you'll need another UART module as the interface.

**Comment by karinadwi** [comment]
Umhum.. I see, you are very helpful:') I will try wistful advice from you one by one. 🙂 Good night and thankyou
